spring:
  application:
    name: turbine
server:
  port: 8989
turbine:
  app-config: ingredient-service
  cluster-name-expression: "'default'"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,
        http://localhost:8762/eureka/