#redis properties
redis:
   url: localhost
   port: 6379
   expiration: 300

#sntp ptoperties
#spring:
#   mail:
#      host: smtp.gmail.com
#      port: 587
#      username: kevinteamhackathon
#      password: MaxedaKevin
#      properties:
#         mail:
#            smnp:
#               auth: true
#               starttls:
#                  enable: true
#                  required: true